api/urls.py
from django.conf.urls import patterns, include, url
from users import urls as users_urls
from django.conf import settings

urlpatterns = patterns('',
    url(r'^', include(users_urls, namespace='api')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

testviews/urls.py
from views import TestSocialView
from django.conf.urls import patterns, url


urlpatterns = patterns('',
    url(r'^test/social_login/$', TestSocialView.as_view(), name='social_login'),
)

users/urls.py
from django.conf.urls import url, patterns, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'accounts', views.UserView)   # user-list

urlpatterns = patterns(
    '',
    url(r'^api/v1/auth/token/', 'rest_framework_jwt.views.obtain_jwt_token', name='auth-token'),
    url(r'^api/v1/auth/social/(?P<backend>[^/]+)/$', views.SocialTokentoJWT.as_view(), name='social-to-auth-token'),
    url(r'^api/v1/', include(router.urls)),

)

testviews/views.py
from django.template.response import TemplateResponse
from django.views.generic import View
from django.conf import settings


class TestSocialView(View):

    def get(self, request):
        context = {
            "fb_id": settings.SOCIAL_AUTH_FACEBOOK_KEY,
        }

        return TemplateResponse(request, 'social_login.html', context)

testviews/templates/social_login.html
{% load subdomainurls %}
<html>
<head>
<script src="https://connect.facebook.net/en_US/all.js" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {

        var api_token;
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (api_token) {
                    xhr.setRequestHeader("Authorization", "JWT " + api_token);
                }
            }
        });

        FB.init({ 
            appId: '{{ fb_id }}', 
            cookie: true, 
            xfbml: true, 
            status: true });

        FB.getLoginStatus(function (response) {
            if (response.authResponse) {
                var fb_token = response.authResponse.accessToken;
                $('#FBAccessToken').val(response.authResponse.accessToken);
                $.post("{% url 'api:social-to-auth-token' backend='facebook' subdomain='api' %}", {access_token: fb_token}, function(returnedData) {
                // This callback is executed if the post was successful
                //self.resolutions.push(resolution);
                api_token = returnedData.token
                $('#APIAccessToken').val(returnedData.token);
                $.get("{% url 'api:user-list' subdomain='api' %}", function(returnedData) {
                    // This callback is executed if the post was successful
                    //self.resolutions.push(resolution);
                    $('#APIData').val(returnedData[0].email);
                }); 
            }); 

            } else {
                // do something...maybe show a login prompt
                $('#FBAccessToken').val('NOT LOGGED IN');
            }
        });

    });
</script>
</head>
<body>
<form action="">
<table>
<tr>
    <td>Facebook AccessToken</td>
    <td>Your username obtained under Auth</td>
</tr>
<tr>
    <td><input id="FBAccessToken" type="text" value="" size="50"/></td>
    <td><input id="APIData" type="text" value="" size="50"/></td>
</tr>
<tr>
    <td colspan="2">Our JWT Access Token</td>
</tr>
<tr>
    <td colspan="2"><input id="APIAccessToken" type="text" value="" size="250"/></td>
</tr>
</table>
</form>
<div id="fb-root"></div>
</body>
</html>